baseURL = "https://youstack.space/"
languageCode = "en-us"
title = "YouStack"
theme = "bento"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "Some thoughts about code"
  description = "Be smart, not tired."

  # Copyright note in the footer
  copyright = "Copyright © 2020 Nick Ker"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/header.jpg"
  ogImage = "images/og_image.jpg"

  # Social media usernames
  github = "Nicolas-DW"
  twitter = "Nicolas_K_DW"

  # Avatar (shown in the homepage)
  avatar = "images/avatar.jpg"
  # Bio is shown in the end of posts
  authorBio = "Nick is a human (until proven otherwise) who likes to code (but not too much, especially if it's not necessary). Follow him on <a href='https://twitter.com/Nicolas_K_DW'>Twitter</a>"
